site_name: documentation
theme:
  name: material
  logo: assets/ALPACA_LOGO2.png
  favicon: assets/logo.png
  font:
   text: Roboto
   code: Red Hat Mono
  palette:
    # Palette toggle for light mode
      primary: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.code.annotate 

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra_css:
  - assets/styles.css

nav:
  - Home: index.md
  - Absolute protein quantification: abs_quant.md
  - Tutorial: Tutorial.md
  - Getting started: getting_started.md
  - Data pre-processing: data_preprocessing.md
  - Quantification: quantification.md
  - Enrichment: enrichment.md
  - Data integration: integration.md